Blog app - integration specs for views and fix n+1 problems
mohametalmeari/i_blog pull request #9
Opened 2023-08-28 09:21 UTC by mohametalmeari

Create Test for: 
- User index page
- User show page
- User post index page
- Post show page

2023-08-28 18:25 UTC, aamirkhan2478 requested changes
Hi @mohametalmeari & @TamaraDimov, 

![](https://media2.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif?cid=ecf05e47k5uapdptg00nidbw3qaxx8iqgsusgaswci2c3uh1&rid=giphy.gif&ct=g)

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
✔️ Good Effort
✔️ Your design is good.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-28 18:25 UTC, aamirkhan2478 commented on test/system/users_test.rb
- [ ] Please write all the tests inside in specs folder because we are using rspec to test our project so kindly add all your integration tests inside the specs folder and then configure it by using this [video](https://www.youtube.com/watch?v=XZkVRkNUFG0&pp=ygUaaG93IHRvIHVzZSBjYXBhYmFyYSBpbiByb3I%3D&ab_channel=StevePolito) :slightly_smiling_face:

2023-08-28 18:25 UTC, aamirkhan2478 commented on test/system/posts_test.rb
- [ ] Please write all the tests inside in specs folder because we are using rspec to test our project so kindly add all your integration tests inside the specs folder and then configure it by using this [video](https://www.youtube.com/watch?v=XZkVRkNUFG0&pp=ygUaaG93IHRvIHVzZSBjYXBhYmFyYSBpbiByb3I%3D&ab_channel=StevePolito) :slightly_smiling_face:

2023-08-28 21:00 UTC, Gambit142 requested changes
Hi @mohametalmeari @TamaraDimov 👋, 

Great work on making the changes requested by a previous reviewer 👏 

## Highlights
- Setup linters correctly ✔️ 
- Installed Capybara gem ✔️ 

You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
_Kindly check the comments under the review._

## Optional suggestions

N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were simply missed by the previous reviewer and addressing them will improve your application._


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### Please tag me in your question so I can receive the notification. You can tag me by typing @Gambit142

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-29 00:06 UTC, mohametalmeari commented
Hi @Gambit142, thank you for the review. I appreciate your effort. However, I don't think there is something wrong with my tests. On my PC, all RSpec tests are passing. You can check the screenshot:

![image](https://github.com/mohametalmeari/i_blog/assets/123117553/369f071b-cdb8-4e62-b76c-581197f50fc6)

I'm testing the database in the seed file. Kindly run this command before running the tests: `rails db:seed` or `rails db:reset`.
For putting the tests of each page in a separate file, I don't think it is a project requirement, and it should not block me from submitting my code. However, I will do it anyway.

2023-08-29 00:28 UTC, mohametalmeari commented on test/system/posts_test.rb
Thank you @aamirkhan2478 for the review.

2023-08-29 01:00 UTC, Reem-lab approved these changes
# Hi @mohametalmeari and @TamaraDimov, 👋🏻👋🏻

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media2.giphy.com/media/3GBG7xejOXhH7MyQkn/giphy.gif"/>

## Highlights

- [x]  Followed Gitflow 💯
- [ ]  Descrtipive PR⭐
- [ ] Kudos for working on the tests for views🤩
- [ ] No Linters error ✅ 
- [ ] N+1 problem solved ⭐
- [ ] Amazing job working on the requested changes 💯

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-29 06:52 UTC, merged

2023-08-29 09:40 UTC, Gambit142 commented
> Hi @Gambit142, thank you for the review. I appreciate your effort. However, I don't think there is something wrong with my tests. On my PC, all RSpec tests are passing. You can check the screenshot:
> 
> ![image](https://user-images.githubusercontent.com/123117553/263861086-369f071b-cdb8-4e62-b76c-581197f50fc6.png)
> 
> I'm testing the database in the seed file. Kindly run this command before running the tests: `rails db:reset RAILS_ENV=test`
> 
> For putting the tests of each page in a separate file, I don't think it is a project requirement, and it should not block me from submitting my code. However, I will do it anyway.

Hi @mohametalmeari, Your tests pass because you have seed data in your database. Kindly note that for our tests to pass, we need data in our database which was not provided until you said we should run the `db/seeds.rb` file. That being said, it would be nice to include the command in your README file. That way anyone that clones your repository will prepopulate the database with data before running your tests. 👍 😎